In [1]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in c:\users\madha\appdata\roaming\python\python312\site-packages (2.1.4)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.13.1)

In [2]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [18]:
df=pd.read_csv(r"C:\Users\madha\Downloads\Water_Potability_Data.csv")

In [19]:
df

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,7.080795,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,333.775777,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,333.775777,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
...,...,...,...,...,...,...,...,...,...,...
100493,8.877281,246.101865,21178.737744,7.765320,343.078182,753.380312,16.941735,60.423472,3.091997,0
100494,7.278621,212.564507,38712.303513,5.798552,262.091710,332.442841,14.053881,70.343043,4.816059,0
100495,7.379448,267.665887,15815.433781,10.525736,333.737272,541.727616,13.361341,54.616800,4.730908,0
100496,6.778115,175.896429,21467.765391,7.103072,349.541131,427.190858,12.543752,55.262978,2.847829,0
100497,7.537867,216.387845,9470.095665,4.987212,341.496198,501.388906,11.258956,52.974783,3.743973,1

In [20]:
df.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,7.080795,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,333.775777,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,333.775777,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

In [21]:
df.tail()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
100493,8.877281,246.101865,21178.737744,7.765320,343.078182,753.380312,16.941735,60.423472,3.091997,0
100494,7.278621,212.564507,38712.303513,5.798552,262.091710,332.442841,14.053881,70.343043,4.816059,0
100495,7.379448,267.665887,15815.433781,10.525736,333.737272,541.727616,13.361341,54.616800,4.730908,0
100496,6.778115,175.896429,21467.765391,7.103072,349.541131,427.190858,12.543752,55.262978,2.847829,0
100497,7.537867,216.387845,9470.095665,4.987212,341.496198,501.388906,11.258956,52.974783,3.743973,1

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100498 entries, 0 to 100497
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ph               100498 non-null  float64
 1   Hardness         100498 non-null  float64
 2   Solids           100498 non-null  float64
 3   Chloramines      100498 non-null  float64
 4   Sulfate          100498 non-null  float64
 5   Conductivity     100498 non-null  float64
 6   Organic_carbon   100498 non-null  float64
 7   Trihalomethanes  100498 non-null  float64
 8   Turbidity        100498 non-null  float64
 9   Potability       100498 non-null  int64
dtypes: float64(9), int64(1)
memory usage: 7.7 MB

In [23]:
df.shape

(100498, 10)

In [24]:
df.isnull().sum()

ph                 0
Hardness           0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [25]:
x=df.iloc[:,:8]
y=df.iloc[:,8]

In [26]:
x

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes
0,7.080795,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970
1,3.716080,129.422921,18630.057858,6.635246,333.775777,592.885359,15.180013,56.329076
2,8.099124,224.236259,19909.541732,9.275884,333.775777,418.606213,16.868637,66.420093
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993
...,...,...,...,...,...,...,...,...
100493,8.877281,246.101865,21178.737744,7.765320,343.078182,753.380312,16.941735,60.423472
100494,7.278621,212.564507,38712.303513,5.798552,262.091710,332.442841,14.053881,70.343043
100495,7.379448,267.665887,15815.433781,10.525736,333.737272,541.727616,13.361341,54.616800
100496,6.778115,175.896429,21467.765391,7.103072,349.541131,427.190858,12.543752,55.262978
100497,7.537867,216.387845,9470.095665,4.987212,341.496198,501.388906,11.258956,52.974783

In [27]:
y

0         2.963135
1         4.500656
2         3.055934
3         4.628771
4         4.075075
            ...
100493    3.091997
100494    4.816059
100495    4.730908
100496    2.847829
100497    3.743973
Name: Turbidity, Length: 100498, dtype: float64

In [28]:
seed=42
test_size=0.25
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=test_size,random_state=seed)

In [ ]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

# Encode target variable if it's continuous or non-integer
le = LabelEncoder()
y_train = le.fit_transform(y_train)  # Converts labels to 0, 1, 2, ...

# Initialize and train the model
model = XGBClassifier()
model.fit(x_train, y_train)

In [30]:
y_pred=model.predict(x_test)
predictions=[round(value) for value in y_pred]
print(predictions)

NotFittedError: need to call fit or load_model beforehand

In [17]:
accuracy=accuracy_score(y_test,predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 76.04%